SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OrderCounts]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[OrderCounts](
	[OrderId] [uniqueidentifier] NOT NULL,
	[ItemName] [nvarchar](255) NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_OrderCounts] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC,
	[ItemName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO