version: '3.4'
 
services:
  exampleapp:
    image: ${DOCKER_REGISTRY-}exampleapp
    build:
      context: .
      dockerfile: ExampleApp/Dockerfile
    environment:
        - "ConnectionStrings:Replica=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Replica1_dev;MultipleActiveResultSets=true;Application Name=Example App Instance 1;"
        - "ConnectionStrings:CommitStore=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Cluster_dev;Integrated Security=SSPI;Application Name=Example App Instance 1;"
        - "ConnectionStrings:AkkaJournal=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Cluster_dev;Integrated Security=SSPI;Application Name=Example App Instance 1;"
        - "ConnectionStrings:AkkaSnapshotStore=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Cluster_dev;Integrated Security=SSPI;Application Name=Example App Instance 1;"

