version: '3.4'

services:
  exampleapp1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/.microsoft/usersecrets/:ro
      - ${APPDATA}/ASP.NET/Https:/.aspnet/https:ro
  exampleapp2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/.microsoft/usersecrets/:ro
      - ${APPDATA}/ASP.NET/Https:/.aspnet/https:ro