version: '3.4'

services:
  exampleapp1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./ExampleApp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Mk6pp4tEEEyyK33ARMTzyzMq
    ports:
      - "80"
      - "443"
    #volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/https:ro
