version: '3.4'
 
services:
  exampleapp1:
    container_name: ExampleApp01
    image: ${DOCKER_REGISTRY-}exampleapp
    ports:
      - "5055"
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: ExampleApp/Dockerfile
    environment:
        # you need to use __ instead of :
        # https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-6.0#environment-variables
        - "ConnectionStrings__Replica=Server=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Replica1_dev;User id=${exampleappsqluser};Password=${exampleappsqlpassword};Application Name=Example App Instance 1;"
        - "ConnectionStrings__CommitStore=Server=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Cluster_dev;User id=${exampleappsqluser};Password=${exampleappsqlpassword};Application Name=Example App Instance 1;"
        - "ConnectionStrings__AkkaJournal=Server=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Cluster_dev;User id=${exampleappsqluser};Password=${exampleappsqlpassword};Application Name=Example App Instance 1;"
        - "ConnectionStrings__AkkaSnapshotStore=Server=hhsrvdione.rvc.ac.uk;Database=ExampleApp_Cluster_dev;User id=${exampleappsqluser};Password=${exampleappsqlpassword};Application Name=Example App Instance 1;"
        - "Akka__ClusterIP=exampleapp1"
        - "Akka__ClusterPort=5055"
        - "Akka__ClusterSeeds=akka.tcp://ExampleApp@exampleapp1:5055,akka.tcp://ExampleApp@exampleapp2:5055"



